execution:
  geth:
    name: ethereum/client-go
    version: v1.13.1
  besu:
    name: hyperledger/besu
    version: 23.7.2
  nethermind:
    name: nethermind/nethermind
    version: 1.20.4
  erigon:
    name: thorax/erigon
    version: v2.49.2
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v4.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.9.2
  teku:
    name: consensys/teku
    version: 23.9.1
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v4.0.8
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v4.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.9.2
  teku:
    name: consensys/teku
    version: 23.9.1
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v4.0.8
